# Generated by Django 3.2.2 on 2021-05-12 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('order', models.IntegerField(default=100000)),
                ('poster', models.ImageField(upload_to='poster')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
